# Generated by Django 5.1.3 on 2024-11-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classified_forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.CharField(choices=[('3-5_days', '3-5 Days'), ('3-5_weeks', '3-5 Weeks')], help_text='Choose the duration of the plan.', max_length=20, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Enter the price of the plan.', max_digits=10)),
                ('discount', models.CharField(blank=True, help_text='Add a discount description (if any).', max_length=100, null=True)),
            ],
        ),
    ]
